import os

# -*- coding: utf-8 -*-
#
# D-Wave(TM) Quantum Computer Docs documentation build configuration file, created by
# sphinx-quickstart on Fri Feb 18 10:52:40 2011.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

sys.path.insert(0, os.path.abspath('.'))

# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.

extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.doctest',
              'sphinx.ext.intersphinx',
              'sphinx.ext.todo',
              'sphinx.ext.ifconfig',
              'sphinx.ext.viewcode',
              'sphinx.ext.mathjax',
              'shared.numsec']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []


# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#html_theme = "default"
html_theme = "dwavedocs"

#html_theme_options = {
#    "rightsidebar": "true",
#    "relbarbgcolor": "black"
#}
# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = ['theme', '../../../shared/theme']

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = '../../../shared/_static/logo_dwave.png'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'D-WaveDocs'
html_add_permalinks = None

# -- Options for LaTeX output --------------------------------------------------

# The paper size ('letter' or 'a4').
#latex_paper_size = 'letter'

# The font size ('10pt', '11pt' or '12pt').
#latex_font_size = '10pt'

copyright = u'D-Wave Systems Inc.'
dwave_name = u'D-Wave Systems Inc.'
dwave_system_name = u'D-Wave$^{\\text{TM}}$ Quantum Computer'

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
  ('index', 'D-WaveDocs.tex', u'%s Documentation' % dwave_system_name,
   dwave_name, 'sphinxdwave'),
]
latex_elements = {
   'fontpkg':''
}


# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = '../../../shared/_static/logo_dwave.png'

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Additional stuff for the LaTeX preamble.
latex_preamble = """
\IfFileExists{sphinx.sty}{
	\usepackage{dwave}

}{}
\def\dwavepart{}
"""

restrictions = """
\def\\restrictions{
              \\textbf{Restrictions on Use, Duplication or Disclosure of Proprietary Information}

              {This document contains information proprietary to D-Wave Systems Inc. or to a third party to which D-Wave Systems
              Inc. may have a legal obligation to protect such information from unauthorized disclosure, use or duplication. Any
              disclosure, use or duplication of this document or any of the information contained herein for other than the specific
              purpose for which it was disclosed is expressly prohibited, except as D-Wave Systems Inc. may otherwise agree to in
              writing.}}
"""

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True

#Allow figure references see http://www.sphinx-doc.org/en/stable/config.html#confval-numfig
numfig = True

latex_additional_files = [os.path.join(os.path.dirname(__file__), 'latex_additional', 'dwave.sty'), ]

# -- Options for manual page output --------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'd-wavedocs', u'D-Wave$^{\\text{TM}}$ Quantum Computer Documentation',
     [u'D-Wave Systems Inc.'], 1)
]


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'http://docs.python.org/': None}

exclude_dirnames = ['.svn', '.git']

rst_prolog = """
.. |name| replace:: replacement *text*
"""

#defines global substitutions
rst_epilog = """
.. |dwave_system_name| unicode:: D-Wave U+2122 U+0020 Quantum U+0020 Computer
.. |dwave_short_tm| unicode:: D-Wave U+2122 U+0020
.. |dwave_2kq| unicode:: D-Wave U+00A0 2000Q
.. |dwave_short| unicode:: D-Wave
.. |dwave_system| unicode:: D-Wave U+00A0 System
.. |dwave_systems_inc| replace:: D-Wave Systems Inc.
.. |support| replace:: dwsupport@dwavesys.com
.. |doc_timing| replace:: *Measuring Computation Time on D-Wave Systems*
.. |doc_pp| replace:: *Postprocessing Methods on D-Wave Systems*
.. |doc_proc| replace:: *Technical Description of the D-Wave Quantum Processing Unit*
.. |doc_qubos| replace:: *Programming with QUBOs*
.. |ui| replace:: Qubist
.. |doc_gs| replace:: *Getting Started with the D-Wave System*
.. |doc_as| replace:: *Application Server Installation Guide*
.. |doc_admin| replace:: *D-Wave System Administrator Guide*
.. |doc_rn_dev| replace:: *D-Wave Release Notes*
.. |nbsp| unicode:: 0xA0
.. |customer| unicode:: U+0020 LANL U+0020
.. |deg| unicode:: U+00B0
.. |doc_spna| replace:: *D-Wave Quantum Computer System Site Preparation (North American Requirements)*
.. |doc_spe| replace:: *D-Wave Quantum Computer System Site Preparation (European Requirements)*
.. |doc_ma| replace:: *D-Wave Quantum Computer System Maintenance Agent Manual*
.. |doc_c| replace:: *Developer Guide for C*
.. |doc_py| replace:: *Developer Guide for Python*
.. |ss| replace:: D-Wave Sampling Service
.. |qc| replace:: D-Wave Quantum Cloud
.. |d_b| replace:: dwave_classical_boltzmann_sampler
.. |d_qb| replace:: dwave_quantum_boltzmann_sampler
.. |wspml| replace:: D-Wave Web Services for Probabilistic Machine Learning
.. |mc| replace:: D-Wave Remote Execution Library
.. |doc_ss| replace:: *Training Probabilistic Machine Learning Models using D-Wave Sampling Libraries*
.. |doc_ws| replace:: *Managing Problems via D-Wave Web Services for PML*
.. |doc_ops| replace:: *D-Wave Quantum Computer Operations*
.. |copy| unicode:: U+000A9 .. COPYRIGHT SIGN
.. |tm| unicode::  U+2122

"""
